# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/knative/pkg/codegen/cmd/injection-gen",
  "github.com/knative/caching/pkg/apis/caching",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
]

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[override]]
  name = "github.com/knative/pkg"
  revision = "0851b95f902d3706fb842fe3160fb697bf5a60e1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.6"

# [[override]]
#   name = "k8s.io/apiserver"
#   version = "kubernetes-1.15.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

#  [[prune.project]]
#   name = "github.com/knative/pkg"
#   unused-packages = false
#   non-go = false
